FROM ubuntu:20.04
MAINTAINER JMA <jmalghem@gmail.com>

RUN apt update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata && apt install -y php php-cli php-fpm php-json php-pdo php-mysql php-zip php-gd  php-mbstring php-curl php-xml php-pear php-bcmath php-mysqli && rm -rf /var/lib/apt/lists/*
RUN mkdir /app
RUN chown -R www-data. /app
COPY conf/vhost.conf /etc/apache2/sites-available/000-default.conf
COPY bin/apache2.sh /usr/local/bin/apache2.sh
CMD ["/usr/local/bin/apache2.sh"]
